#!/bin/sh -e

sysconfig_dir="$ROOT/etc"

## /etc/modules

f="$sysconfig_dir/modules"
if prepare_file "$f"; then
	begin_header "$f"

	cat >>"$f" <<'_EOF'

# conntrack
nf_conntrack
nf_conntrack_amanda
nf_conntrack_ftp
nf_conntrack_h323
nf_conntrack_irc
nf_conntrack_pptp
nf_conntrack_sip
nf_conntrack_snmp
nf_conntrack_tftp

nf_conntrack_netbios_ns
nf_conntrack_sane

# nat
nf_nat
nf_nat_amanda
nf_nat_ftp
nf_nat_h323
nf_nat_irc
nf_nat_pptp
nf_nat_sip
nf_nat_snmp_basic
nf_nat_tftp

_EOF

	end_header "$f"

	# CentOS/RHEL 7+ does not have /etc/modules
	t="$sysconfig_dir/modules-load.d"
	if [ -d "$t" ] && t="$t/modules.conf" && [ ! "$f" -ef "$t" ]; then
		relative_path "$f" "$t" f
		ln -sf "$f" "$t"
	fi
fi

## Adjust filesystem ownership and permissions

# $ROOT/etc/sudoers.d/10-netctl-reiptables
adj_rights '' 0440 "$sysconfig_dir/sudoers.d/10-netctl-reiptables"

[ "$INSTALL_EUID" != 0 ] && owner='' || owner="root:$RECONFIGURE_GROUP"

# $DEST/netctl/etc/reiptables/
adj_rights "$owner" 2775 \
	"$DEST/netctl/etc/reiptables/data/usrxml" \
	"$DEST/netctl/etc/reiptables/data/usrxml/ipset" \
	"$DEST/netctl/etc/reiptables/data/usrxml/iptables" \
	"$DEST/netctl/etc/reiptables/data/usrxml/ip6tables"

adj_rights "$owner" 0664 \
	"$DEST/netctl/etc/reiptables/data/usrxml/usr.xml"

return 0
