#!/bin/sh -e

sysconfig_dir="$ROOT/etc"

## /etc/modules

f="$sysconfig_dir/modules"
if prepare_file "$f"; then
	begin_header "$f"

	cat >>"$f" <<'_EOF'

# conntrack
nf_conntrack_amanda
nf_conntrack_ftp
nf_conntrack_h323
nf_conntrack_irc
nf_conntrack_pptp
nf_conntrack_sip
nf_conntrack_snmp
nf_conntrack_tftp

nf_conntrack_netbios_ns
nf_conntrack_sane

# nat
nf_nat_amanda
nf_nat_ftp
nf_nat_h323
nf_nat_irc
nf_nat_pptp
nf_nat_sip
nf_nat_snmp_basic
nf_nat_tftp

_EOF

	end_header "$f"
fi

## Adjust filesystem ownership and permissions

# $ROOT/etc/sudoers.d/10-netctl-reiptables
adj_rights '' 0440 "$ROOT/etc/sudoers.d/10-netctl-reiptables"

[ "$INSTALL_EUID" != 0 ] && owner='' || owner="root:$RECONFIGURE_GROUP"

return 0
